name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install exiftool
        run: sudo apt-get install -y exiftool

      - name: Make image-info Executable
        run: chmod +x ./scripts/image-info
        working-directory: blog

      - name: Build and Run Image Info Exe
        run: ./scripts/image-info.exe
        working-directory: blog

      - name: Checkout destination
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.131.0/hugo_0.131.0_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo
          mv ${RUNNER_TEMP}/hugo /usr/local/bin/hugo

      - name: Build
        run: hugo
        working-directory: blog

      - name: Deploy
        run: |
          cp -R blog/public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'Guanox'
          git config user.email 'kajprintz@gmail.com'
          git commit -m 'Updated site'
          git push
